# -*- coding: utf-8 -*-
"""Generate giant test file, write in chunks of 1000 lines"""
import os

TARGET_FILE = "examples/giant_test.py"
CHUNK_LINES = 1000

header = '''# -*- coding: utf-8 -*-
"""
Giant test file for testing MyCoder with large complex code
Total lines: ~5000
Contains: algorithms, data structures, design patterns, math, etc.
"""
import os, sys, json, math, random, time, datetime, hashlib
import functools, itertools, collections, re, uuid, base64
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union, Callable
from abc import ABC, abstractmethod
from contextlib import contextmanager
from dataclasses import dataclass, field
from enum import Enum, auto
from collections import defaultdict, OrderedDict, deque

'''

def gen_funcs(start, count):
    lines = []
    for i in range(start, start + count):
        lines.append('')
        lines.append('def func_%04d(x: int, y: int = 0) -> int:' % i)
        lines.append('    """Function %04d: performs calculation %d"""' % (i, i))
        lines.append('    result = x')
        lines.append('    for _ in range(max(1, y %% 50)):')
        lines.append('        result = (result * 17 + %d * 11) %% 1000000007' % i)
        lines.append('    return result')
    return '\n'.join(lines)

def gen_classes(start, count):
    lines = []
    for i in range(start, start + count):
        lines.append('')
        lines.append('class Class_%04d:' % i)
        lines.append('    """Class %04d: data container"""' % i)
        lines.append('    def __init__(self, value: Any = None):')
        lines.append('        self.value = value')
        lines.append('        self._id = %d' % i)
        lines.append('        self.data = dict()')
        lines.append('        self.history = []')
        lines.append('')
        lines.append('    def set(self, key: str, val: Any) -> None:')
        lines.append('        self.data[key] = val')
        lines.append('        self.history.append(("set", key, val))')
        lines.append('')
        lines.append('    def get(self, key: str, default: Any = None) -> Any:')
        lines.append('        return self.data.get(key, default)')
        lines.append('')
        lines.append('    def stats(self) -> Dict[str, Any]:')
        lines.append('        return dict(id=self._id, entries=len(self.data), ops=len(self.history))')
        lines.append('')
        lines.append('    def __repr__(self) -> str:')
        lines.append('        return "Class_%04d(id={}, entries={})".format(self._id, len(self.data))' % i)
    return '\n'.join(lines)

def gen_algorithms(start, count):
    lines = []
    lines.append('')
    lines.append('# ========== Sorting Algorithms Module [%d-%d] ==========' % (start, start + count))
    lines.append('')

    # bubble sort
    lines.append('def bubble_sort_%04d(arr: List[int]) -> List[int]:' % start)
    lines.append('    """Bubble sort %d"""' % start)
    lines.append('    n = len(arr)')
    lines.append('    for i in range(n):')
    lines.append('        for j in range(n - i - 1):')
    lines.append('            if arr[j] > arr[j + 1]:')
    lines.append('                arr[j], arr[j + 1] = arr[j + 1], arr[j]')
    lines.append('    return arr')
    lines.append('')

    # quick sort
    lines.append('def quick_sort_%04d(arr: List[int]) -> List[int]:' % start)
    lines.append('    """Quick sort %d"""' % start)
    lines.append('    if len(arr) <= 1:')
    lines.append('        return arr')
    lines.append('    pivot = arr[len(arr) // 2]')
    lines.append('    left = [x for x in arr if x < pivot]')
    lines.append('    middle = [x for x in arr if x == pivot]')
    lines.append('    right = [x for x in arr if x > pivot]')
    lines.append('    return quick_sort_%04d(left) + middle + quick_sort_%04d(right)' % (start, start))
    lines.append('')

    # merge sort
    lines.append('def merge_sort_%04d(arr: List[int]) -> List[int]:' % start)
    lines.append('    """Merge sort %d"""' % start)
    lines.append('    if len(arr) <= 1:')
    lines.append('        return arr')
    lines.append('    mid = len(arr) // 2')
    lines.append('    left = merge_sort_%04d(arr[:mid])' % start)
    lines.append('    right = merge_sort_%04d(arr[mid:])' % start)
    lines.append('    result = []')
    lines.append('    i = j = 0')
    lines.append('    while i < len(left) and j < len(right):')
    lines.append('        if left[i] <= right[j]:')
    lines.append('            result.append(left[i])')
    lines.append('            i += 1')
    lines.append('        else:')
    lines.append('            result.append(right[j])')
    lines.append('            j += 1')
    lines.append('    result.extend(left[i:])')
    lines.append('    result.extend(right[j:])')
    lines.append('    return result')
    lines.append('')

    # binary search
    lines.append('def binary_search_%04d(arr: List[int], target: int) -> int:' % start)
    lines.append('    """Binary search %d"""' % start)
    lines.append('    lo, hi = 0, len(arr) - 1')
    lines.append('    while lo <= hi:')
    lines.append('        mid = (lo + hi) // 2')
    lines.append('        if arr[mid] == target:')
    lines.append('            return mid')
    lines.append('        if arr[mid] < target:')
    lines.append('            lo = mid + 1')
    lines.append('        else:')
    lines.append('            hi = mid - 1')
    lines.append('    return -1')
    lines.append('')

    # linear search
    lines.append('def linear_search_%04d(arr: List[Any], target: Any) -> int:' % start)
    lines.append('    """Linear search %d"""' % start)
    lines.append('    for i, item in enumerate(arr):')
    lines.append('        if item == target:')
    lines.append('            return i')
    lines.append('    return -1')
    lines.append('')

    # heap sort
    lines.append('def heap_sort_%04d(arr: List[int]) -> List[int]:' % start)
    lines.append('    """Heap sort %d"""' % start)
    lines.append('    import heapq')
    lines.append('    result = []')
    lines.append('    for item in arr:')
    lines.append('        heapq.heappush(result, item)')
    lines.append('    return [heapq.heappop(result) for _ in range(len(result))]')
    lines.append('')

    # insertion sort
    lines.append('def insertion_sort_%04d(arr: List[int]) -> List[int]:' % start)
    lines.append('    """Insertion sort %d"""' % start)
    lines.append('    for i in range(1, len(arr)):')
    lines.append('        key = arr[i]')
    lines.append('        j = i - 1')
    lines.append('        while j >= 0 and arr[j] > key:')
    lines.append('            arr[j + 1] = arr[j]')
    lines.append('            j -= 1')
    lines.append('        arr[j + 1] = key')
    lines.append('    return arr')
    lines.append('')

    # selection sort
    lines.append('def selection_sort_%04d(arr: List[int]) -> List[int]:' % start)
    lines.append('    """Selection sort %d"""' % start)
    lines.append('    for i in range(len(arr)):')
    lines.append('        min_idx = i')
    lines.append('        for j in range(i + 1, len(arr)):')
    lines.append('            if arr[j] < arr[min_idx]:')
    lines.append('                min_idx = j')
    lines.append('        arr[i], arr[min_idx] = arr[min_idx], arr[i]')
    lines.append('    return arr')
    lines.append('')

    # counting sort
    lines.append('def counting_sort_%04d(arr: List[int]) -> List[int]:' % start)
    lines.append('    """Counting sort %d"""' % start)
    lines.append('    if not arr:')
    lines.append('        return arr')
    lines.append('    max_val = max(arr)')
    lines.append('    count = [0] * (max_val + 1)')
    lines.append('    for num in arr:')
    lines.append('        count[num] += 1')
    lines.append('    result = []')
    lines.append('    for i, c in enumerate(count):')
    lines.append('        result.extend([i] * c)')
    lines.append('    return result')
    lines.append('')

    # radix sort
    lines.append('def radix_sort_%04d(arr: List[int]) -> List[int]:' % start)
    lines.append('    """Radix sort %d"""' % start)
    lines.append('    if not arr:')
    lines.append('        return arr')
    lines.append('    max_val = max(arr)')
    lines.append('    exp = 1')
    lines.append('    while max_val // exp > 0:')
    lines.append('        buckets = [[] for _ in range(10)]')
    lines.append('        for num in arr:')
    lines.append('            idx = (num // exp) %% 10')
    lines.append('            buckets[idx].append(num)')
    lines.append('        arr = [x for b in buckets for x in b]')
    lines.append('        exp *= 10')
    lines.append('    return arr')

    return '\n'.join(lines)

def gen_design_patterns(start, count):
    lines = []
    lines.append('')
    lines.append('# ========== Design Patterns Module [%d-%d] ==========' % (start, start + count))
    lines.append('')

    # Singleton
    lines.append('class Singleton_%04d:' % start)
    lines.append('    """Singleton pattern %d"""' % start)
    lines.append('    _instance = None')
    lines.append('    def __new__(cls, *args, **kwargs):')
    lines.append('        if cls._instance is None:')
    lines.append('            cls._instance = super().__new__(cls)')
    lines.append('        return cls._instance')
    lines.append('')

    # Factory
    lines.append('class Factory_%04d:' % start)
    lines.append('    """Factory pattern %d"""' % start)
    lines.append('    @staticmethod')
    lines.append('    def create(product_type: str, **kwargs) -> Any:')
    lines.append('        types = dict(')
    lines.append('            dict=lambda: dict(**kwargs),')
    lines.append('            list=lambda: list(kwargs.values()),')
    lines.append('            set=lambda: set(kwargs.values()),')
    lines.append('            tuple=lambda: tuple(kwargs.values()),')
    lines.append('        )')
    lines.append('        return types.get(product_type, lambda: kwargs)()')
    lines.append('')

    # Builder
    lines.append('class Builder_%04d:' % start)
    lines.append('    """Builder pattern %d"""' % start)
    lines.append('    def __init__(self):')
    lines.append('        self._data = dict()')
    lines.append('    def add(self, key: str, value: Any) -> "Builder_%04d":' % start)
    lines.append('        self._data[key] = value')
    lines.append('        return self')
    lines.append('    def build(self) -> dict:')
    lines.append('        return self._data.copy()')
    lines.append('')

    # Observer
    lines.append('class Observer_%04d:' % start)
    lines.append('    """Observer pattern %d"""' % start)
    lines.append('    def __init__(self):')
    lines.append('        self._observers = []')
    lines.append('    def attach(self, observer: Callable) -> None:')
    lines.append('        self._observers.append(observer)')
    lines.append('    def detach(self, observer: Callable) -> None:')
    lines.append('        if observer in self._observers:')
    lines.append('            self._observers.remove(observer)')
    lines.append('    def notify(self, event: Any) -> None:')
    lines.append('        for obs in self._observers:')
    lines.append('            obs(event)')
    lines.append('')

    # Strategy
    lines.append('class Strategy_%04d(ABC):' % start)
    lines.append('    """Strategy pattern %d"""' % start)
    lines.append('    @abstractmethod')
    lines.append('    def execute(self, data: Any) -> Any:')
    lines.append('        pass')
    lines.append('')

    lines.append('class StrategyA_%04d(Strategy_%04d):' % (start, start))
    lines.append('    def execute(self, data: Any) -> Any:')
    lines.append('        return str(data).upper()')
    lines.append('')

    lines.append('class StrategyB_%04d(Strategy_%04d):' % (start, start))
    lines.append('    def execute(self, data: Any) -> Any:')
    lines.append('        return str(data).lower()')
    lines.append('')

    # Decorator
    lines.append('class Decorator_%04d:' % start)
    lines.append('    """Decorator pattern %d"""' % start)
    lines.append('    def __init__(self, component):')
    lines.append('        self._component = component')
    lines.append('    def operation(self) -> str:')
    lines.append('        return "[Decorated] " + str(self._component.operation())')
    lines.append('')

    # Adapter
    lines.append('class Adapter_%04d:' % start)
    lines.append('    """Adapter pattern %d"""' % start)
    lines.append('    def __init__(self, adaptee):')
    lines.append('        self._adaptee = adaptee')
    lines.append('    def request(self, data: Any) -> Any:')
    lines.append('        return self._adaptee.specific_request(data)')
    lines.append('')

    # Proxy
    lines.append('class Proxy_%04d:' % start)
    lines.append('    """Proxy pattern %d"""' % start)
    lines.append('    def __init__(self, real_subject):')
    lines.append('        self._real = real_subject')
    lines.append('        self._cache = dict()')
    lines.append('    def request(self, key: Any) -> Any:')
    lines.append('        if key not in self._cache:')
    lines.append('            self._cache[key] = self._real.request(key)')
    lines.append('        return self._cache[key]')
    lines.append('')

    # Command
    lines.append('class Command_%04d(ABC):' % start)
    lines.append('    """Command pattern %d"""' % start)
    lines.append('    @abstractmethod')
    lines.append('    def execute(self) -> Any:')
    lines.append('        pass')
    lines.append('')

    lines.append('class CompositeCommand_%04d(Command_%04d):' % (start, start))
    lines.append('    """Composite command pattern %d"""' % start)
    lines.append('    def __init__(self):')
    lines.append('        self._commands = []')
    lines.append('    def add(self, cmd: Command_%04d) -> None:' % start)
    lines.append('        self._commands.append(cmd)')
    lines.append('    def execute(self) -> List[Any]:')
    lines.append('        return [cmd.execute() for cmd in self._commands]')
    lines.append('')

    # State Machine
    lines.append('class StateMachine_%04d:' % start)
    lines.append('    """State machine pattern %d"""' % start)
    lines.append('    def __init__(self):')
    lines.append('        self._states = dict()')
    lines.append('        self._current = None')
    lines.append('    def add_state(self, name: str, transitions: dict) -> None:')
    lines.append('        self._states[name] = transitions')
    lines.append('        if self._current is None:')
    lines.append('            self._current = name')
    lines.append('    def transition(self, event: str) -> Optional[str]:')
    lines.append('        if self._current and event in self._states.get(self._current, dict()):')
    lines.append('            self._current = self._states[self._current][event]')
    lines.append('        return self._current')
    lines.append('')

    # Chain of Responsibility
    lines.append('class ChainOfResponsibility_%04d:' % start)
    lines.append('    """Chain of responsibility pattern %d"""' % start)
    lines.append('    def __init__(self):')
    lines.append('        self._handlers = []')
    lines.append('    def add_handler(self, handler: Callable) -> None:')
    lines.append('        self._handlers.append(handler)')
    lines.append('    def handle(self, request: Any) -> Any:')
    lines.append('        for handler in self._handlers:')
    lines.append('            result = handler(request)')
    lines.append('            if result is not None:')
    lines.append('                return result')
    lines.append('        return None')

    return '\n'.join(lines)

def gen_data_structures(start, count):
    lines = []
    lines.append('')
    lines.append('# ========== Data Structures Module [%d-%d] ==========' % (start, start + count))
    lines.append('')

    # ListNode
    lines.append('class ListNode_%04d:' % start)
    lines.append('    """Linked list node %d"""' % start)
    lines.append('    def __init__(self, val: Any = 0, next_node=None):')
    lines.append('        self.val = val')
    lines.append('        self.next = next_node')
    lines.append('')

    # LinkedList
    lines.append('class LinkedList_%04d:' % start)
    lines.append('    """Linked list %d"""' % start)
    lines.append('    def __init__(self):')
    lines.append('        self.head = None')
    lines.append('        self._size = 0')
    lines.append('    def append(self, val: Any) -> None:')
    lines.append('        node = ListNode_%04d(val)' % start)
    lines.append('        if not self.head:')
    lines.append('            self.head = node')
    lines.append('        else:')
    lines.append('            cur = self.head')
    lines.append('            while cur.next:')
    lines.append('                cur = cur.next')
    lines.append('            cur.next = node')
    lines.append('        self._size += 1')
    lines.append('    def prepend(self, val: Any) -> None:')
    lines.append('        node = ListNode_%04d(val, self.head)' % start)
    lines.append('        self.head = node')
    lines.append('        self._size += 1')
    lines.append('    def delete(self, val: Any) -> bool:')
    lines.append('        if not self.head:')
    lines.append('            return False')
    lines.append('        if self.head.val == val:')
    lines.append('            self.head = self.head.next')
    lines.append('            self._size -= 1')
    lines.append('            return True')
    lines.append('        cur = self.head')
    lines.append('        while cur.next:')
    lines.append('            if cur.next.val == val:')
    lines.append('                cur.next = cur.next.next')
    lines.append('                self._size -= 1')
    lines.append('                return True')
    lines.append('            cur = cur.next')
    lines.append('        return False')
    lines.append('    def find(self, val: Any):')
    lines.append('        cur = self.head')
    lines.append('        while cur:')
    lines.append('            if cur.val == val:')
    lines.append('                return cur')
    lines.append('            cur = cur.next')
    lines.append('        return None')
    lines.append('    def to_list(self) -> List[Any]:')
    lines.append('        result = []')
    lines.append('        cur = self.head')
    lines.append('        while cur:')
    lines.append('            result.append(cur.val)')
    lines.append('            cur = cur.next')
    lines.append('        return result')
    lines.append('    def __len__(self) -> int:')
    lines.append('        return self._size')
    lines.append('    def __iter__(self):')
    lines.append('        cur = self.head')
    lines.append('        while cur:')
    lines.append('            yield cur.val')
    lines.append('            cur = cur.next')
    lines.append('')

    # TreeNode
    lines.append('class TreeNode_%04d:' % start)
    lines.append('    """Tree node %d"""' % start)
    lines.append('    def __init__(self, val: Any = 0, left=None, right=None):')
    lines.append('        self.val = val')
    lines.append('        self.left = left')
    lines.append('        self.right = right')
    lines.append('')

    # BinaryTree
    lines.append('class BinaryTree_%04d:' % start)
    lines.append('    """Binary tree %d"""' % start)
    lines.append('    def __init__(self):')
    lines.append('        self.root = None')
    lines.append('    def insert(self, val: Any) -> None:')
    lines.append('        if not self.root:')
    lines.append('            self.root = TreeNode_%04d(val)' % start)
    lines.append('        else:')
    lines.append('            self._insert_rec(self.root, val)')
    lines.append('    def _insert_rec(self, node, val: Any) -> None:')
    lines.append('        if val < node.val:')
    lines.append('            if node.left:')
    lines.append('                self._insert_rec(node.left, val)')
    lines.append('            else:')
    lines.append('                node.left = TreeNode_%04d(val)' % start)
    lines.append('        else:')
    lines.append('            if node.right:')
    lines.append('                self._insert_rec(node.right, val)')
    lines.append('            else:')
    lines.append('                node.right = TreeNode_%04d(val)' % start)
    lines.append('    def inorder(self) -> List[Any]:')
    lines.append('        result = []')
    lines.append('        def dfs(node):')
    lines.append('            if node:')
    lines.append('                dfs(node.left)')
    lines.append('                result.append(node.val)')
    lines.append('                dfs(node.right)')
    lines.append('        dfs(self.root)')
    lines.append('        return result')
    lines.append('    def preorder(self) -> List[Any]:')
    lines.append('        result = []')
    lines.append('        def dfs(node):')
    lines.append('            if node:')
    lines.append('                result.append(node.val)')
    lines.append('                dfs(node.left)')
    lines.append('                dfs(node.right)')
    lines.append('        dfs(self.root)')
    lines.append('        return result')
    lines.append('    def postorder(self) -> List[Any]:')
    lines.append('        result = []')
    lines.append('        def dfs(node):')
    lines.append('            if node:')
    lines.append('                dfs(node.left)')
    lines.append('                dfs(node.right)')
    lines.append('                result.append(node.val)')
    lines.append('        dfs(self.root)')
    lines.append('        return result')
    lines.append('    def level_order(self) -> List[List[Any]]:')
    lines.append('        if not self.root:')
    lines.append('            return []')
    lines.append('        result = []')
    lines.append('        queue = deque([self.root])')
    lines.append('        while queue:')
    lines.append('            level = []')
    lines.append('            for _ in range(len(queue)):')
    lines.append('                node = queue.popleft()')
    lines.append('                level.append(node.val)')
    lines.append('                if node.left:')
    lines.append('                    queue.append(node.left)')
    lines.append('                if node.right:')
    lines.append('                    queue.append(node.right)')
    lines.append('            result.append(level)')
    lines.append('        return result')
    lines.append('    def height(self) -> int:')
    lines.append('        def dfs(node):')
    lines.append('            if not node:')
    lines.append('                return 0')
    lines.append('            return 1 + max(dfs(node.left), dfs(node.right))')
    lines.append('        return dfs(self.root)')
    lines.append('    def search(self, val: Any) -> bool:')
    lines.append('        def dfs(node):')
    lines.append('            if not node:')
    lines.append('                return False')
    lines.append('            if node.val == val:')
    lines.append('                return True')
    lines.append('            return dfs(node.left) or dfs(node.right)')
    lines.append('        return dfs(self.root)')
    lines.append('')

    # Trie
    lines.append('class TrieNode_%04d:' % start)
    lines.append('    """Trie node %d"""' % start)
    lines.append('    def __init__(self):')
    lines.append('        self.children = dict()')
    lines.append('        self.is_end = False')
    lines.append('')

    lines.append('class Trie_%04d:' % start)
    lines.append('    """Trie %d"""' % start)
    lines.append('    def __init__(self):')
    lines.append('        self.root = TrieNode_%04d()' % start)
    lines.append('    def insert(self, word: str) -> None:')
    lines.append('        node = self.root')
    lines.append('        for ch in word:')
    lines.append('            if ch not in node.children:')
    lines.append('                node.children[ch] = TrieNode_%04d()' % start)
    lines.append('            node = node.children[ch]')
    lines.append('        node.is_end = True')
    lines.append('    def search(self, word: str) -> bool:')
    lines.append('        node = self.root')
    lines.append('        for ch in word:')
    lines.append('            if ch not in node.children:')
    lines.append('                return False')
    lines.append('            node = node.children[ch]')
    lines.append('        return node.is_end')
    lines.append('    def starts_with(self, prefix: str) -> bool:')
    lines.append('        node = self.root')
    lines.append('        for ch in prefix:')
    lines.append('            if ch not in node.children:')
    lines.append('                return False')
    lines.append('            node = node.children[ch]')
    lines.append('        return True')
    lines.append('    def get_all_words(self) -> List[str]:')
    lines.append('        result = []')
    lines.append('        def dfs(node, path):')
    lines.append('            if node.is_end:')
    lines.append('                result.append("".join(path))')
    lines.append('            for ch, child in node.children.items():')
    lines.append('                path.append(ch)')
    lines.append('                dfs(child, path)')
    lines.append('                path.pop()')
    lines.append('        dfs(self.root, [])')
    lines.append('        return result')
    lines.append('')

    # Graph
    lines.append('class Graph_%04d:' % start)
    lines.append('    """Graph %d"""' % start)
    lines.append('    def __init__(self, directed: bool = False):')
    lines.append('        self.adj = defaultdict(list)')
    lines.append('        self.directed = directed')
    lines.append('        self._vertices = 0')
    lines.append('    def add_vertex(self, v: Any) -> None:')
    lines.append('        if v not in self.adj:')
    lines.append('            self.adj[v] = []')
    lines.append('            self._vertices += 1')
    lines.append('    def add_edge(self, u: Any, v: Any, weight: float = 1.0) -> None:')
    lines.append('        self.add_vertex(u)')
    lines.append('        self.add_vertex(v)')
    lines.append('        self.adj[u].append((v, weight))')
    lines.append('        if not self.directed:')
    lines.append('            self.adj[v].append((u, weight))')
    lines.append('    def bfs(self, start: Any) -> List[Any]:')
    lines.append('        visited = set()')
    lines.append('        queue = deque([start])')
    lines.append('        result = []')
    lines.append('        while queue:')
    lines.append('            node = queue.popleft()')
    lines.append('            if node not in visited:')
    lines.append('                visited.add(node)')
    lines.append('                result.append(node)')
    lines.append('                for neighbor, _ in self.adj[node]:')
    lines.append('                    if neighbor not in visited:')
    lines.append('                        queue.append(neighbor)')
    lines.append('        return result')
    lines.append('    def dfs(self, start: Any) -> List[Any]:')
    lines.append('        visited = set()')
    lines.append('        result = []')
    lines.append('        def _dfs(node):')
    lines.append('            visited.add(node)')
    lines.append('            result.append(node)')
    lines.append('            for neighbor, _ in self.adj[node]:')
    lines.append('                if neighbor not in visited:')
    lines.append('                    _dfs(neighbor)')
    lines.append('        _dfs(start)')
    lines.append('        return result')
    lines.append('    def shortest_path(self, start: Any, end: Any):')
    lines.append('        import heapq')
    lines.append('        dist = {start: 0}')
    lines.append('        prev = dict()')
    lines.append('        pq = [(0, start)]')
    lines.append('        visited = set()')
    lines.append('        while pq:')
    lines.append('            d, node = heapq.heappop(pq)')
    lines.append('            if node in visited:')
    lines.append('                continue')
    lines.append('            visited.add(node)')
    lines.append('            if node == end:')
    lines.append('                break')
    lines.append('            for neighbor, w in self.adj[node]:')
    lines.append('                nd = d + w')
    lines.append('                if neighbor not in dist or nd < dist[neighbor]:')
    lines.append('                    dist[neighbor] = nd')
    lines.append('                    prev[neighbor] = node')
    lines.append('                    heapq.heappush(pq, (nd, neighbor))')
    lines.append('        if end not in prev and start != end:')
    lines.append('            return None')
    lines.append('        path = [end]')
    lines.append('        cur = end')
    lines.append('        while cur in prev:')
    lines.append('            cur = prev[cur]')
    lines.append('            path.append(cur)')
    lines.append('        return list(reversed(path))')
    lines.append('    def has_cycle(self) -> bool:')
    lines.append('        visited = set()')
    lines.append('        rec_stack = set()')
    lines.append('        def dfs(node):')
    lines.append('            visited.add(node)')
    lines.append('            rec_stack.add(node)')
    lines.append('            for neighbor, _ in self.adj[node]:')
    lines.append('                if neighbor not in visited:')
    lines.append('                    if dfs(neighbor):')
    lines.append('                        return True')
    lines.append('                elif neighbor in rec_stack:')
    lines.append('                    return True')
    lines.append('            rec_stack.remove(node)')
    lines.append('            return False')
    lines.append('        for v in self.adj:')
    lines.append('            if v not in visited:')
    lines.append('                if dfs(v):')
    lines.append('                    return True')
    lines.append('        return False')
    lines.append('    def __len__(self) -> int:')
    lines.append('        return self._vertices')
    lines.append('    def edges(self) -> List[Tuple]:')
    lines.append('        result = []')
    lines.append('        for u in self.adj:')
    lines.append('            for v, w in self.adj[u]:')
    lines.append('                if self.directed or u <= v:')
    lines.append('                    result.append((u, v, w))')
    lines.append('        return result')

    return '\n'.join(lines)

# Delete old file
if os.path.exists(TARGET_FILE):
    os.remove(TARGET_FILE)

# Write header first
with open(TARGET_FILE, 'w', encoding='utf-8') as f:
    f.write(header)

# Generate sections
sections = []
sections.append(gen_funcs(1, 100))
sections.append(gen_funcs(101, 100))
sections.append(gen_algorithms(1, 10))
sections.append(gen_classes(1, 8))
sections.append(gen_design_patterns(1, 5))
sections.append(gen_data_structures(1, 3))
sections.append(gen_funcs(201, 100))
sections.append(gen_classes(9, 8))
sections.append(gen_funcs(301, 100))
sections.append(gen_algorithms(11, 10))
sections.append(gen_funcs(401, 100))
sections.append(gen_classes(17, 8))

# Write in chunks of 1000 lines
buffer = []
current_lines = 0
chunk_num = 0

for section in sections:
    section_lines = section.split('\n')
    buffer.extend(section_lines)
    current_lines += len(section_lines)
    
    while current_lines >= CHUNK_LINES:
        chunk_num += 1
        with open(TARGET_FILE, 'a', encoding='utf-8') as f:
            chunk_data = buffer[:CHUNK_LINES]
            f.write('\n'.join(chunk_data) + '\n')
        buffer = buffer[CHUNK_LINES:]
        current_lines -= CHUNK_LINES
        print("Written chunk %d: %d lines -> %s" % (chunk_num, CHUNK_LINES, TARGET_FILE))

# Write remaining content
if buffer:
    chunk_num += 1
    with open(TARGET_FILE, 'a', encoding='utf-8') as f:
        f.write('\n'.join(buffer) + '\n')
    print("Written final chunk %d: %d lines -> %s" % (chunk_num, len(buffer), TARGET_FILE))

# Statistics
total = sum(1 for _ in open(TARGET_FILE, 'r', encoding='utf-8'))
file_size = os.path.getsize(TARGET_FILE) / 1024
print("\nDone! Total lines: %d, Size: %.1f KB" % (total, file_size))